In [1]:
import numpy as np
import pandas as pd

In [2]:
user_data = {
    "MarksA": np.random.randint(1,100,5),
    "MarksB": np.random.randint(50,100,5),
    "MarksC": np.random.randint(1,100,5)
}
print(user_data)

{'MarksA': array([11, 43, 51, 90, 16]), 'MarksB': array([87, 78, 61, 70, 91]), 'MarksC': array([11, 80, 16, 53,  9])}


In [3]:
df = pd.DataFrame(user_data)
print(df)

   MarksA  MarksB  MarksC
0      11      87      11
1      43      78      80
2      51      61      16
3      90      70      53
4      16      91       9


In [4]:
df.head()

MarksA  MarksB  MarksC
0      11      87      11
1      43      78      80
2      51      61      16
3      90      70      53
4      16      91       9

In [5]:
df.describe()

MarksA    MarksB   MarksC
count   5.000000   5.00000   5.0000
mean   42.200000  77.40000  33.8000
std    31.712773  12.25969  31.4436
min    11.000000  61.00000   9.0000
25%    16.000000  70.00000  11.0000
50%    43.000000  78.00000  16.0000
75%    51.000000  87.00000  53.0000
max    90.000000  91.00000  80.0000

In [6]:
df.tail()

MarksA  MarksB  MarksC
0      11      87      11
1      43      78      80
2      51      61      16
3      90      70      53
4      16      91       9

In [7]:
df.tail(n=2)

MarksA  MarksB  MarksC
3      90      70      53
4      16      91       9

### Accessing A Row

In [8]:
df.iloc[3]

MarksA    90
MarksB    70
MarksC    53
Name: 3, dtype: int32

### Accessing A Row & A Column

In [9]:
df.iloc[3,1]

70

In [10]:
df.iloc[3][1]

70

In [11]:
idx = df.columns.get_loc("MarksB")
print(df.iloc[3,idx])

70


In [12]:
idx = [df.columns.get_loc("MarksB"), df.columns.get_loc("MarksC")]
print(df.iloc[3,idx])

MarksB    70
MarksC    53
Name: 3, dtype: int32


In [13]:
df.iloc[:3,idx]

MarksB  MarksC
0      87      11
1      78      80
2      61      16

In [14]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0      87      11
1      78      80
2      61      16

### Sorting The Dataframe

In [15]:
df.sort_values(by=["MarksA"], ascending=True)

MarksA  MarksB  MarksC
0      11      87      11
4      16      91       9
1      43      78      80
2      51      61      16
3      90      70      53

In [16]:
df.sort_values(by=["MarksA"], ascending=False)

MarksA  MarksB  MarksC
3      90      70      53
2      51      61      16
1      43      78      80
4      16      91       9
0      11      87      11

In [17]:
df.sort_values(by=["MarksC", "MarksA"], ascending=True)

MarksA  MarksB  MarksC
4      16      91       9
0      11      87      11
2      51      61      16
3      90      70      53
1      43      78      80

In [18]:
df.sort_values(by=["MarksC", "MarksA"], ascending=False)

MarksA  MarksB  MarksC
1      43      78      80
3      90      70      53
2      51      61      16
0      11      87      11
4      16      91       9

### Dataframe To Numpy Arrays

In [19]:
data_array = df.values
print(data_array)

[[11 87 11]
 [43 78 80]
 [51 61 16]
 [90 70 53]
 [16 91  9]]


In [20]:
print(type(df))
print(df.shape)

print(type(data_array))
print(data_array.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)
<class 'numpy.ndarray'>
(5, 3)


In [21]:
print(data_array[2][2])

16


### Numpy Array To Dataframe

In [22]:
new_df = pd.DataFrame(data_array, dtype='int32', columns=["Physics", "Chemistry", "Maths"])

In [23]:
new_df.head()

Physics  Chemistry  Maths
0       11         87     11
1       43         78     80
2       51         61     16
3       90         70     53
4       16         91      9

In [24]:
new_df.to_csv("PCM.csv", index=False)

In [25]:
pcm = pd.read_csv("PCM.csv")

In [26]:
pcm.head()

Physics  Chemistry  Maths
0       11         87     11
1       43         78     80
2       51         61     16
3       90         70     53
4       16         91      9