### Working With Numpy - For Mathematical Operations !

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]])

In [6]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [7]:
print(b.shape)

(5, 1)


In [8]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
print(c.shape)

(2, 3)


In [10]:
print(c[1][1])

5


In [11]:
# Create Arrays Of Zeros, Ones, Custom
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
c = np.full((3,4), 5)

In [14]:
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# Identity Matrix (Size/Square Matrix)
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Random Matrix

randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.71453398 0.35070439 0.18429509]
 [0.86268057 0.61285234 0.22140806]]


In [17]:
print(randomMatrix[:,1])

[0.35070439 0.61285234]


In [18]:
print(randomMatrix[1,1:])

[0.61285234 0.22140806]


In [19]:
randomMatrix[1,1:] = 1
print(randomMatrix)

[[0.71453398 0.35070439 0.18429509]
 [0.86268057 1.         1.        ]]


In [20]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
z[1,:] = 5
print(z)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [22]:
z[:,-1] = 7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [23]:
# Data Types
print(z.dtype)

float64


In [24]:
z = np.zeros((4,4), dtype='int64')
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
print(z.dtype)

int64


#### Mathematical Operations

In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [27]:
print(x+y)

[[ 6  8]
 [10 12]]


In [28]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [29]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [30]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [31]:
print(x*y)

[[ 5 12]
 [21 32]]


In [32]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [33]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [34]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


#### Matrix Multiplication & Dot Products

In [36]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [37]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [38]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [39]:
# Multiplication Of Vectors

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [40]:
print(sum(a))

10


In [41]:
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [42]:
print(np.sum(x, axis=0))

[4 6]


In [43]:
print(np.sum(x, axis=1))

[3 7]


#### Stacking Of Arrays

In [44]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [45]:
print(np.stack((a,b),axis=1))

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [46]:
print(np.stack((a,b),axis=0))

[[ 1  2  3  4]
 [ 1  4  9 16]]


#### Reshape

In [47]:
a = np.stack((a,b),axis=0)
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [48]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [49]:
a = a.reshape((-1,4))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]
