## Numpy Random Module

- **rand**    :  Random Values In A Given Shape.
- **randn**   :  Return A Sample (Or Samples) From The "Standard Normal" Distribution.
- **randint** :  Return Random Integers From Low (Inclusive) To High (Exclusive).
- **random**  :  Return Random Floats In The Half-Open Interval [0.0, 1.0).
- **choice**  :  Generates A Random Sample From A Given 1-D Array.
- **shuffle** :  Shuffles The Contents Of A Sequence.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [4]:
# shuffle

np.random.shuffle(a)
print(a)

[13 14  5  8 10  6 11  7  9 12]


In [5]:
np.random.shuffle(a)
print(a)

[ 5 12  8  6 14 13  7  9 11 10]


In [6]:
# rand

a = np.random.rand(2,3)

In [7]:
print(a)

[[0.11051597 0.12622524 0.37548301]
 [0.64925976 0.58001782 0.01811643]]


In [8]:
# randn

a = np.random.randn(2,3)
print(a)

[[-0.90154691  0.33192123 -1.0773281 ]
 [-0.22739397 -1.11430845  1.43456048]]


In [9]:
#randint
a = np.random.randint(5,10,3)
print(a)

[6 8 9]


In [10]:
# choice
element = np.random.choice([1,2,3,5,6,3,5,7,8])
print(element)

2


In [11]:
print(np.random.random(10))

[0.62466487 0.75713289 0.6113505  0.06826471 0.25117852 0.86442578
 0.09456375 0.38314351 0.46303993 0.25554952]


## Seed :-- Store The State Of The Random Machine

- Help In Replicating The Same Results

In [12]:
np.random.seed(1)

In [13]:
print(np.random.random(10))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [14]:
print(np.random.random(10))

[0.41919451 0.6852195  0.20445225 0.87811744 0.02738759 0.67046751
 0.4173048  0.55868983 0.14038694 0.19810149]


In [15]:
print(np.random.random(10))

[0.80074457 0.96826158 0.31342418 0.69232262 0.87638915 0.89460666
 0.08504421 0.03905478 0.16983042 0.8781425 ]
