## 4. Broadcasting

- Adding a Scalar to a Vector, Numpy will Add it to Each Element in the Vector
- x + a = xi + a
- Similarly Add a Vector to a Matrix, Numpy will Add the Vector to Each Column of the Matrix.

In [1]:
import numpy as np

x = np.array([1,2,3,4])
X = np.array([[10,20,30,40],[40,50,60,70]])

In [2]:
print(x)

[1 2 3 4]


In [3]:
print(x+4)

[5 6 7 8]


In [4]:
print(X)

[[10 20 30 40]
 [40 50 60 70]]


In [5]:
print(X+x)

[[11 22 33 44]
 [41 52 63 74]]


## 5. Matrix Multiplication (Dot Product)

- C = AB is Only Defined when the Second Dimension of A Matches the First Dimension of B.
- If A is of Shape (m,n) and B is of Shape (n,p), then C is of Shape (m,p).
- C[i,j] = Summation[k] A[i,k] B[k,j]
- C[i,j] is Computed by Taking Dot Product of i-th Row of A With j-th Column of B.
- Matrix Multiplication is Linear Combination of Columns of A Weighted by Column Entries of B.

In [6]:
A = np.array([[1,2],
             [3,4]])

B = np.array([[0,2],
             [3,2]])

C = np.dot(A,B)
print(C)

[[ 6  6]
 [12 14]]


## 6. Element Wise Multiplication : Hadamard Product

- C [ i ][ j ] = A [ i ][ j ] * B [ i ][ j ]

In [7]:
A = np.array([[1,2],
             [3,4]])

B = np.array([[0,2],
             [3,2]])

print(A*B)

[[0 4]
 [9 8]]
