## 7. Norms

- **Norms** can be Thought of as a Proxy For Size of a Vector.
    - L^P Norm => ||x||p => (Summation(|xi|^p))^(1/p)
- Norm is a Function that Maps Vectors to Non-Negative Values. A Norm Satisfies the Following Properties :
    - f(x) = 0 => x = 0
    - f(x+y) <= f(x) + f(y) (Triangle Inequality)
    - For all 'alpha' in R, f(alpha, x) = |alpha| f(x)
- L^2 Norm is called the **Euclidean Norm**, denotes as **||x||** or **||x||^2**
    - Square L^2 Norm => **(x.T) x**
    - Derivative of Squared L^2 Norm => 2*x (Easier to Work With)
    - Squared L^2 Norm Grows Very Slowly near the Origin.
- L^1 Norm is the Absolute Sum of All Members of a Vector
- **Max-Norm** : L^(inf) : This Simplifies to Absolute Value of the Element with Highest Magnitude.

In [1]:
import numpy as np

In [2]:
x = np.array([3,4])

lp2 = np.linalg.norm(x)
print(lp2)

5.0


In [3]:
lp1 = np.linalg.norm(x, ord=1)
print(lp1)

7.0


In [4]:
lpinf = np.linalg.norm(x, ord=np.inf)
print(lpinf)

4.0


## 8. Determinants

In [5]:
A = np.array([[1,2],[3,4]])
print(np.linalg.det(A))

-2.0000000000000004


## 9. Inverse

In [6]:
Ainv = np.linalg.inv(A)
print(Ainv)
print(np.dot(A,Ainv)) # (A.A^-1 = I)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [7]:
# Pseudo Inverse
pinv = np.linalg.pinv(A)
print(pinv)
print(np.dot(A,pinv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.00000000e+00 -6.66133815e-16]
 [ 1.77635684e-15  1.00000000e+00]]


In [8]:
# Determinant -> 0
Ao = np.array([[6,8],[3,4]])

In [9]:
# Aoinv = np.linalg.inv(Ao)
Aoinv = np.linalg.pinv(Ao)
print(Aoinv)
print(np.dot(A,Aoinv))

[[0.048 0.024]
 [0.064 0.032]]
[[0.176 0.088]
 [0.4   0.2  ]]


## 10. Linear Equations

In [10]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])

# 2x + 3y = 8
# 3x + 1y = 5

In [11]:
print(np.linalg.solve(a,b))

[1. 2.]
